### ISSUE TITLE
Main tracking issue for Corrode port to Rust

### ISSUE THREAD

**Issue by tcr** [tcr/corollary#1]
There's a lot of small tasks to get to the end, but I roughly think this is the roadmap. Comment below if you're interested in helping out!

Look at [language_c.rs](https://github.com/tcr/corrode-but-in-rust/blob/master/out/language_c.rs) and [corrode.rs](https://github.com/tcr/corrode-but-in-rust/blob/master/out/corrode.rs) for the state of the automated conversion.

* [x] Automate bulk cross-compilation as modules (see the `out/` directory for current status)
* [x] Write a proof-of-concept parser for Haskell and compilation to Rust
* [x] Support functions, variables, literals, types
* [x] Support case statements and guards
* [x] Convert instances and data structures correctly
* [ ] Detect pointfree code and convert it into pointwise
* [x] Properly convert $ and . operators
* [ ] Convert rest of operators into Rust equivalents or fn wrappers
* [x] Successfully parse all files (except lexer.x parser.y) (failures currently output as // ERROR)
* [x] Find a way to parse flex-based lexer.x and parser.y files and cross-compile them
* [ ] Switch to *manual* conversion for all remaining edge cases (tricky code segments, clever monad use, etc.)
* [ ] Pass language-c test bench
* [ ] Pass corrode test bench
* [ ] Port literate Haskell comments into Rust
* [ ] Feature-complete

**Comment by pshc** [comment]
Hi! paupau here.

**Comment by tcr** [comment]
Hey @pshc (paupau)! So this is a rough checklist of like... big tasks that have to happen.

Practically speaking, the compiler is sloppy so I've been looking at the output of [language_c.rs](https://github.com/tcr/corrode-but-in-rust/blob/master/out/language_c.rs) and comparing it to [language-c](https://github.com/acowley/language-c/tree/b375a2e3f60668698fa0be7366278f35fca3dba1/src/Language/C). Find the most egregious examples of bad code, fix `main.rs` to output better or more correct Rust code, and then rerunning the output. Try `cargo run "./language-c/src/Language/C" > out/language_c.rs` to update the converted file.

There's also the case that some files in Haskell can't be parsed; this project uses [LALRPOP](https://github.com/nikomatsakis/lalrpop) for parsing and can be updated. `cargo test -- --nocapture` tests one .hs file at a time so you can see why it's outputting `// ERROR` code.

Then there's stuff around how to convert operators properly, outputting enums, and more. I'm happy to answer any questions about the architecture (it's bad, needs to be improved) or the endgoal of the project!

**Comment by pshc** [comment]
Cool! I'll start playing with the code.

**Comment by pshc** [comment]
The output is pretty nice! And it's all single pass? Crazy.

I guess my first question: How is it going to figure out ownership? e.g. from the test code

```rust
    #[derive(Clone, Debug)]
    struct Ident(String, isize, NodeInfo);

    fn identToString(Ident(s, _, _): Ident) -> String {
        s
    }
```

Maybe `identToString(&Ident) -> Cow<'a, str>` would be superior in some situations, but in others you might really want to move `Ident`...

**Comment by pshc** [comment]
Heh what's the deal with `"@@WEIRD BAD BASE64 STR@@"`? Parser doesn't support char literals yet?

**Comment by tcr** [comment]
Yeah, one idea was to use heap-allocated Strings everywhere as the MVP, then removing the rest in the manual code step. But, obviously better if string ownership were handled intelligently. (I wrote `test/input.hs` by pulling out actual code from Corrode, hoping to actually compile the resulting Rust, but having to auto-ref the match arm to match on &str literals and likewise box the "name" arg made that trickier. Adding `.into()` to everything gets you partway there, but what a hack!)

String handling: I had an exhausting fight with LALRPOP to parse escaped characters in strings and character literals properly. The quick fix was regex'ing strings in a preprocess step, expanding them to contain their base64 converted version (e.g. "Efhj=" and 'A9'), and then decoding them during the AST translation. This actually works decently. The character literal decoding is wrong and should be easy to fix—definitely a good starting point!

**Comment by tcr** [comment]
After #9 and #13, all of Corrode's files (listed in main.rs) can be parsed. There's now a testbed, so run `cargo test` to see if there are any regressions in parsing.

My next goal is to fix the hacks added into the LALRPOP file to finish this parsing, since I think that is necessary before parsing 100% of .hs files in `language-c` as well.

**Comment by tcr** [comment]
Okay, this is pretty much out of date so I'm closing this—might be time for a new roadmap, just focused on Corollary.
